//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Autor { get; set; }
        public int CountShop { get; set; }
        public int CountStock { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
        public int Cost { get; set; }
    }
}
